### ISSUE TITLE
update Security Check translation

### ISSUE THREAD

**Issue by teds-mitre** [mitre/ckl2POAM#9]
Please update ckl2POAM to address bug in eMASS where POAM imports successfully but does not link CKL to POAM in Assets > Findings > Benchmarks whenever column F Security Check contains more than the syntax or 15 character limit of SV-#####r#_rule For example, 
FAIL: SV-90187r2_rule, V-75507
PASS: SV-90187r2_rule

**Comment by teds-mitre** [comment]
note that the new syntax of SV numbering should also be supported, believe that's SV-XXXXXXrXXXXXX

**Comment by camdenmoors** [comment]
> note that the new syntax of SV numbering should also be supported, believe that's SV-XXXXXXrXXXXXX

Just to clarify, should I pad the revision number with 0s? Or should this just work if a vulnerability with that type of SVID is passed?

**Comment by ejaronne** [comment]
I defer to @teds-mitre on the allowed items, but I'm guessing we need to accommodate both old and new rule ids. For example, the older Windows 10 STIG for the same Rule Title: "The Take ownership of files or other objects user right must only be assigned to the Administrators group.":

Has this for v1r19 benchmark ca. 25 Oct 2019: "SV-78431r1_rule"
But this for v2r1 benchmark ca. 13 Nov 2020: "SV-220983r569187_rule"

So, I'm pretty sure we're not forcing the longer format, just be able to provide whatever the ckl gives you, nothing more?

**Comment by teds-mitre** [comment]
agreed @ejaronne

**Comment by camdenmoors** [comment]
Closing as completed in https://github.com/mitre/ckl2POAM/commit/01a3150fd8676e7642d3349f594f7c39f0028ddf.
